### ISSUE TITLE
Installation halts at last step

### ISSUE THREAD

**Issue by smeisler** [mandymejia/BayesGLMfMRI#14]
Hello,

Really excited to try this out! I am having trouble installing BayesfMRI, however.

# Error
## Command
`devtools::install_github("mandymejia/BayesfMRI")`

## Output
```
Downloading GitHub repo mandymejia/BayesfMRI@HEAD
Skipping 1 packages not available: INLA
   checking for file ���/tmp/RtmpGjRkoP/remotes1953761726bd/mandymejia-BayesfMRI-d1f72ce/DES���  checking for file ���/tmp/RtmpGjRkoP/remotes1953761726bd/mandymejia-BayesfMRI-d1f72ce/DESCRIPTION��� (1.1s)
���  preparing ���BayesfMRI���: (465ms)
���  checking DESCRIPTION meta-information..
���  checking for LF line-endings in source and make files and shell scripts (415ms)
���  checking for empty or unneeded directories
���  building ���BayesfMRI_0.1.8.tar.gz���
   Warning in sprintf(gettext(fmt, domain = domain), ...) :
     one argument not used by format 'invalid uid value replaced by that for user 'nobody''
   Warning: invalid uid value replaced by that for user 'nobody'
   Warning in sprintf(gettext(fmt, domain = domain), ...) :
     one argument not used by format 'invalid gid value replaced by that for user 'nobody''
   Warning: invalid gid value replaced by that for user 'nobody'

* installing *source* package ���BayesfMRI��� ...
** using staged installation
** R
** data
*** moving datasets to lazyload DB
** inst
** byte-compile and prepare package for lazy loading
Error: object ���convert_to_dlabel��� is not exported by 'namespace:ciftiTools'
Execution halted
ERROR: lazy loading failed for package ���BayesfMRI���
* removing ���/rdma/vast-rdma/vast/gablab/smeisler/anaconda3/envs/r-new/lib/R/library/BayesfMRI���
Warning message:
In i.p(...) :
  installation of package ���/tmp/Rtmpe3BMZm/filedabf70af67aa/BayesfMRI_0.1.8.tar.gz��� had non-zero exit status

```
# Steps to replicate
1) Download HCP workbench
2) Create R environment in Anaconda with the `conda-forge` R 4.1.2 base installation
3) `install.packages(devtools)`
4) `install.packages("INLA", repos=c(getOption("repos"), INLA="https://inla.r-inla-download.org/R/testing"))` - Note I changed it to testing branch from stable, since I am on R 4.1
5) A few dependencies had to be independently installed via conda-forge before `devtools` and `INLA` were completely finished
6) `devtools::install_github("mandymejia/BayesfMRI")` - ciftiTools and remaining dependencies were installed successfully through this, but at the very last step I get that error.

# More info
I am using a fresh anaconda environment running on a Linux CentOs7.6 HPC. Happy to provide more info as needed. Hope we can get to the bottom of this!

Best,
Steven

**Comment by smeisler** [comment]
Removing `importFrom(ciftiTools,convert_to_dlabel)` from NAMESPACE has enabled me to install the package. Not sure what consequences that will have down the line....

**Comment by danieladamspencer** [comment]
Hi Steven,

This error comes from the fact that the `ciftiTools` package has been updated on CRAN, and the `convert_to_dlabel` function is deprecated and is now replaced by `convert_xifti`. Thank you for pointing this out! We will be fixing this very soon.

All the best,
Dan

**Comment by damondpham** [comment]
This should be fixed on the master branch now! Thanks @smeisler for pointing out this problem.

**Comment by smeisler** [comment]
Installation works, thanks for the fast response, closing the issue!
