### ISSUE TITLE
How to get started?

### ISSUE THREAD

**Issue by CarlosAndres12** [mandymejia/BayesGLMfMRI#31]
Kind regards.

Is there any vignette or example on how to use the package?

Thanks.

**Comment by damondpham** [comment]
Hi @CarlosAndres12 !

Unfortunately we don't have a vignette yet. But if you let me know how you'd like to use the package, perhaps with attaching example data via Google Drive or something, I can send you some example code.

In general `BayesGLM` or `BayesGLM_cifti` is the main function to use, but maybe in your case it's different.

**Comment by CarlosAndres12** [comment]
Hi @damondpham, I am just starting with fMRI, so I was looking which libraries were available in R, right now I don't have any data.

Thanks for your pronely response.

**Comment by damondpham** [comment]
Gotcha! Our lab has several packages for fMRI: https://github.com/mandymejia?tab=repositories . Feel free to open a new issue or email one of us if you come across any questions!
